// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: skellycam.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "skellycam";

/** Log severity levels */
export enum LogLevel {
  TRACE = 0,
  DEBUG = 1,
  INFO = 2,
  SUCCESS = 3,
  WARNING = 4,
  ERROR = 5,
  CRITICAL = 6,
  UNRECOGNIZED = -1,
}

/** Request for starting frame streaming */
export interface MultiFrameRequest {
  /** Optional display image sizes for each camera */
  displayImageSizes: { [key: string]: CameraDisplaySize };
  /** Last received frame number for resuming stream */
  lastReceivedFrameNumber: number;
}

export interface MultiFrameRequest_DisplayImageSizesEntry {
  key: string;
  value: CameraDisplaySize | undefined;
}

/** Camera display size information */
export interface CameraDisplaySize {
  width: number;
  height: number;
}

/** MultiFrame response containing camera images */
export interface MultiFrameResponse {
  /** MultiFrame metadata */
  frameNumber: number;
  cameraGroupId: string;
  timestamp: number;
  /** Camera frames */
  cameraFrames: CameraMultiFrame[];
}

/** Individual camera frame */
export interface CameraMultiFrame {
  cameraId: string;
  cameraIndex: number;
  imageWidth: number;
  imageHeight: number;
  colorChannels: number;
  jpegData: Uint8Array;
}

/** MultiFrame acknowledgment from client */
export interface MultiFrameAcknowledgment {
  frameNumber: number;
  displayImageSizes: { [key: string]: CameraDisplaySize };
}

export interface MultiFrameAcknowledgment_DisplayImageSizesEntry {
  key: string;
  value: CameraDisplaySize | undefined;
}

/** Acknowledgment response */
export interface AcknowledgmentResponse {
  success: boolean;
}

/** Request for log streaming */
export interface LogRequest {
  /** Minimum log level to receive */
  minLevel: LogLevel;
}

/** Log record message */
export interface LogRecord {
  name: string;
  message: string;
  args: string[];
  levelName: string;
  levelNo: number;
  pathname: string;
  filename: string;
  module: string;
  excInfo: string;
  excText: string;
  stackInfo: string;
  lineNo: number;
  funcName: string;
  created: number;
  msecs: number;
  relativeCreated: number;
  thread: number;
  threadName: string;
  processName: string;
  process: number;
  deltaT: string;
  formattedMessage: string;
  asctime: string;
  type: string;
}

/** Request for framerate updates */
export interface FramerateRequest {
  /** Optional camera group ID to filter updates */
  cameraGroupId: string;
}

/** Framerate update message */
export interface FramerateUpdate {
  cameraGroupId: string;
  backendFramerate: FramerateData | undefined;
  frontendFramerate: FramerateData | undefined;
}

/** Framerate data */
export interface FramerateData {
  fps: number;
  frameTimeMs: number;
  source: string;
  recentFrameDurations: number[];
}

function createBaseMultiFrameRequest(): MultiFrameRequest {
  return { displayImageSizes: {}, lastReceivedFrameNumber: 0 };
}

export const MultiFrameRequest: MessageFns<MultiFrameRequest> = {
  encode(message: MultiFrameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    Object.entries(message.displayImageSizes).forEach(([key, value]) => {
      MultiFrameRequest_DisplayImageSizesEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    if (message.lastReceivedFrameNumber !== 0) {
      writer.uint32(16).int64(message.lastReceivedFrameNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiFrameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiFrameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = MultiFrameRequest_DisplayImageSizesEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.displayImageSizes[entry1.key] = entry1.value;
          }
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lastReceivedFrameNumber = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MultiFrameRequest>): MultiFrameRequest {
    return MultiFrameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MultiFrameRequest>): MultiFrameRequest {
    const message = createBaseMultiFrameRequest();
    message.displayImageSizes = Object.entries(object.displayImageSizes ?? {}).reduce<
      { [key: string]: CameraDisplaySize }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = CameraDisplaySize.fromPartial(value);
      }
      return acc;
    }, {});
    message.lastReceivedFrameNumber = object.lastReceivedFrameNumber ?? 0;
    return message;
  },
};

function createBaseMultiFrameRequest_DisplayImageSizesEntry(): MultiFrameRequest_DisplayImageSizesEntry {
  return { key: "", value: undefined };
}

export const MultiFrameRequest_DisplayImageSizesEntry: MessageFns<MultiFrameRequest_DisplayImageSizesEntry> = {
  encode(message: MultiFrameRequest_DisplayImageSizesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      CameraDisplaySize.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiFrameRequest_DisplayImageSizesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiFrameRequest_DisplayImageSizesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = CameraDisplaySize.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MultiFrameRequest_DisplayImageSizesEntry>): MultiFrameRequest_DisplayImageSizesEntry {
    return MultiFrameRequest_DisplayImageSizesEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MultiFrameRequest_DisplayImageSizesEntry>): MultiFrameRequest_DisplayImageSizesEntry {
    const message = createBaseMultiFrameRequest_DisplayImageSizesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? CameraDisplaySize.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseCameraDisplaySize(): CameraDisplaySize {
  return { width: 0, height: 0 };
}

export const CameraDisplaySize: MessageFns<CameraDisplaySize> = {
  encode(message: CameraDisplaySize, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.width !== 0) {
      writer.uint32(13).float(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(21).float(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CameraDisplaySize {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCameraDisplaySize();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.width = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.height = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CameraDisplaySize>): CameraDisplaySize {
    return CameraDisplaySize.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CameraDisplaySize>): CameraDisplaySize {
    const message = createBaseCameraDisplaySize();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseMultiFrameResponse(): MultiFrameResponse {
  return { frameNumber: 0, cameraGroupId: "", timestamp: 0, cameraFrames: [] };
}

export const MultiFrameResponse: MessageFns<MultiFrameResponse> = {
  encode(message: MultiFrameResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameNumber !== 0) {
      writer.uint32(8).int64(message.frameNumber);
    }
    if (message.cameraGroupId !== "") {
      writer.uint32(18).string(message.cameraGroupId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(25).double(message.timestamp);
    }
    for (const v of message.cameraFrames) {
      CameraMultiFrame.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiFrameResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiFrameResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frameNumber = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cameraGroupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.timestamp = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cameraFrames.push(CameraMultiFrame.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MultiFrameResponse>): MultiFrameResponse {
    return MultiFrameResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MultiFrameResponse>): MultiFrameResponse {
    const message = createBaseMultiFrameResponse();
    message.frameNumber = object.frameNumber ?? 0;
    message.cameraGroupId = object.cameraGroupId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.cameraFrames = object.cameraFrames?.map((e) => CameraMultiFrame.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCameraMultiFrame(): CameraMultiFrame {
  return { cameraId: "", cameraIndex: 0, imageWidth: 0, imageHeight: 0, colorChannels: 0, jpegData: new Uint8Array(0) };
}

export const CameraMultiFrame: MessageFns<CameraMultiFrame> = {
  encode(message: CameraMultiFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraId !== "") {
      writer.uint32(10).string(message.cameraId);
    }
    if (message.cameraIndex !== 0) {
      writer.uint32(16).int32(message.cameraIndex);
    }
    if (message.imageWidth !== 0) {
      writer.uint32(24).int32(message.imageWidth);
    }
    if (message.imageHeight !== 0) {
      writer.uint32(32).int32(message.imageHeight);
    }
    if (message.colorChannels !== 0) {
      writer.uint32(40).int32(message.colorChannels);
    }
    if (message.jpegData.length !== 0) {
      writer.uint32(50).bytes(message.jpegData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CameraMultiFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCameraMultiFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cameraId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cameraIndex = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.imageWidth = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.imageHeight = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.colorChannels = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.jpegData = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CameraMultiFrame>): CameraMultiFrame {
    return CameraMultiFrame.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CameraMultiFrame>): CameraMultiFrame {
    const message = createBaseCameraMultiFrame();
    message.cameraId = object.cameraId ?? "";
    message.cameraIndex = object.cameraIndex ?? 0;
    message.imageWidth = object.imageWidth ?? 0;
    message.imageHeight = object.imageHeight ?? 0;
    message.colorChannels = object.colorChannels ?? 0;
    message.jpegData = object.jpegData ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMultiFrameAcknowledgment(): MultiFrameAcknowledgment {
  return { frameNumber: 0, displayImageSizes: {} };
}

export const MultiFrameAcknowledgment: MessageFns<MultiFrameAcknowledgment> = {
  encode(message: MultiFrameAcknowledgment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameNumber !== 0) {
      writer.uint32(8).int64(message.frameNumber);
    }
    Object.entries(message.displayImageSizes).forEach(([key, value]) => {
      MultiFrameAcknowledgment_DisplayImageSizesEntry.encode({ key: key as any, value }, writer.uint32(18).fork())
        .join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiFrameAcknowledgment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiFrameAcknowledgment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frameNumber = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = MultiFrameAcknowledgment_DisplayImageSizesEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.displayImageSizes[entry2.key] = entry2.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MultiFrameAcknowledgment>): MultiFrameAcknowledgment {
    return MultiFrameAcknowledgment.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MultiFrameAcknowledgment>): MultiFrameAcknowledgment {
    const message = createBaseMultiFrameAcknowledgment();
    message.frameNumber = object.frameNumber ?? 0;
    message.displayImageSizes = Object.entries(object.displayImageSizes ?? {}).reduce<
      { [key: string]: CameraDisplaySize }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = CameraDisplaySize.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseMultiFrameAcknowledgment_DisplayImageSizesEntry(): MultiFrameAcknowledgment_DisplayImageSizesEntry {
  return { key: "", value: undefined };
}

export const MultiFrameAcknowledgment_DisplayImageSizesEntry: MessageFns<
  MultiFrameAcknowledgment_DisplayImageSizesEntry
> = {
  encode(
    message: MultiFrameAcknowledgment_DisplayImageSizesEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      CameraDisplaySize.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiFrameAcknowledgment_DisplayImageSizesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiFrameAcknowledgment_DisplayImageSizesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = CameraDisplaySize.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(
    base?: DeepPartial<MultiFrameAcknowledgment_DisplayImageSizesEntry>,
  ): MultiFrameAcknowledgment_DisplayImageSizesEntry {
    return MultiFrameAcknowledgment_DisplayImageSizesEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<MultiFrameAcknowledgment_DisplayImageSizesEntry>,
  ): MultiFrameAcknowledgment_DisplayImageSizesEntry {
    const message = createBaseMultiFrameAcknowledgment_DisplayImageSizesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? CameraDisplaySize.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseAcknowledgmentResponse(): AcknowledgmentResponse {
  return { success: false };
}

export const AcknowledgmentResponse: MessageFns<AcknowledgmentResponse> = {
  encode(message: AcknowledgmentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcknowledgmentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcknowledgmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AcknowledgmentResponse>): AcknowledgmentResponse {
    return AcknowledgmentResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AcknowledgmentResponse>): AcknowledgmentResponse {
    const message = createBaseAcknowledgmentResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseLogRequest(): LogRequest {
  return { minLevel: 0 };
}

export const LogRequest: MessageFns<LogRequest> = {
  encode(message: LogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minLevel !== 0) {
      writer.uint32(8).int32(message.minLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.minLevel = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LogRequest>): LogRequest {
    return LogRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LogRequest>): LogRequest {
    const message = createBaseLogRequest();
    message.minLevel = object.minLevel ?? 0;
    return message;
  },
};

function createBaseLogRecord(): LogRecord {
  return {
    name: "",
    message: "",
    args: [],
    levelName: "",
    levelNo: 0,
    pathname: "",
    filename: "",
    module: "",
    excInfo: "",
    excText: "",
    stackInfo: "",
    lineNo: 0,
    funcName: "",
    created: 0,
    msecs: 0,
    relativeCreated: 0,
    thread: 0,
    threadName: "",
    processName: "",
    process: 0,
    deltaT: "",
    formattedMessage: "",
    asctime: "",
    type: "",
  };
}

export const LogRecord: MessageFns<LogRecord> = {
  encode(message: LogRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    for (const v of message.args) {
      writer.uint32(26).string(v!);
    }
    if (message.levelName !== "") {
      writer.uint32(34).string(message.levelName);
    }
    if (message.levelNo !== 0) {
      writer.uint32(40).int32(message.levelNo);
    }
    if (message.pathname !== "") {
      writer.uint32(50).string(message.pathname);
    }
    if (message.filename !== "") {
      writer.uint32(58).string(message.filename);
    }
    if (message.module !== "") {
      writer.uint32(66).string(message.module);
    }
    if (message.excInfo !== "") {
      writer.uint32(74).string(message.excInfo);
    }
    if (message.excText !== "") {
      writer.uint32(82).string(message.excText);
    }
    if (message.stackInfo !== "") {
      writer.uint32(90).string(message.stackInfo);
    }
    if (message.lineNo !== 0) {
      writer.uint32(96).int32(message.lineNo);
    }
    if (message.funcName !== "") {
      writer.uint32(106).string(message.funcName);
    }
    if (message.created !== 0) {
      writer.uint32(113).double(message.created);
    }
    if (message.msecs !== 0) {
      writer.uint32(121).double(message.msecs);
    }
    if (message.relativeCreated !== 0) {
      writer.uint32(129).double(message.relativeCreated);
    }
    if (message.thread !== 0) {
      writer.uint32(136).int64(message.thread);
    }
    if (message.threadName !== "") {
      writer.uint32(146).string(message.threadName);
    }
    if (message.processName !== "") {
      writer.uint32(154).string(message.processName);
    }
    if (message.process !== 0) {
      writer.uint32(160).int32(message.process);
    }
    if (message.deltaT !== "") {
      writer.uint32(170).string(message.deltaT);
    }
    if (message.formattedMessage !== "") {
      writer.uint32(178).string(message.formattedMessage);
    }
    if (message.asctime !== "") {
      writer.uint32(186).string(message.asctime);
    }
    if (message.type !== "") {
      writer.uint32(194).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.args.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.levelName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.levelNo = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.pathname = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.module = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.excInfo = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.excText = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.stackInfo = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.lineNo = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.funcName = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 113) {
            break;
          }

          message.created = reader.double();
          continue;
        }
        case 15: {
          if (tag !== 121) {
            break;
          }

          message.msecs = reader.double();
          continue;
        }
        case 16: {
          if (tag !== 129) {
            break;
          }

          message.relativeCreated = reader.double();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.thread = longToNumber(reader.int64());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.threadName = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.processName = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.process = reader.int32();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.deltaT = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.formattedMessage = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.asctime = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LogRecord>): LogRecord {
    return LogRecord.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LogRecord>): LogRecord {
    const message = createBaseLogRecord();
    message.name = object.name ?? "";
    message.message = object.message ?? "";
    message.args = object.args?.map((e) => e) || [];
    message.levelName = object.levelName ?? "";
    message.levelNo = object.levelNo ?? 0;
    message.pathname = object.pathname ?? "";
    message.filename = object.filename ?? "";
    message.module = object.module ?? "";
    message.excInfo = object.excInfo ?? "";
    message.excText = object.excText ?? "";
    message.stackInfo = object.stackInfo ?? "";
    message.lineNo = object.lineNo ?? 0;
    message.funcName = object.funcName ?? "";
    message.created = object.created ?? 0;
    message.msecs = object.msecs ?? 0;
    message.relativeCreated = object.relativeCreated ?? 0;
    message.thread = object.thread ?? 0;
    message.threadName = object.threadName ?? "";
    message.processName = object.processName ?? "";
    message.process = object.process ?? 0;
    message.deltaT = object.deltaT ?? "";
    message.formattedMessage = object.formattedMessage ?? "";
    message.asctime = object.asctime ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseFramerateRequest(): FramerateRequest {
  return { cameraGroupId: "" };
}

export const FramerateRequest: MessageFns<FramerateRequest> = {
  encode(message: FramerateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraGroupId !== "") {
      writer.uint32(10).string(message.cameraGroupId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FramerateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFramerateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cameraGroupId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FramerateRequest>): FramerateRequest {
    return FramerateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FramerateRequest>): FramerateRequest {
    const message = createBaseFramerateRequest();
    message.cameraGroupId = object.cameraGroupId ?? "";
    return message;
  },
};

function createBaseFramerateUpdate(): FramerateUpdate {
  return { cameraGroupId: "", backendFramerate: undefined, frontendFramerate: undefined };
}

export const FramerateUpdate: MessageFns<FramerateUpdate> = {
  encode(message: FramerateUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraGroupId !== "") {
      writer.uint32(10).string(message.cameraGroupId);
    }
    if (message.backendFramerate !== undefined) {
      FramerateData.encode(message.backendFramerate, writer.uint32(18).fork()).join();
    }
    if (message.frontendFramerate !== undefined) {
      FramerateData.encode(message.frontendFramerate, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FramerateUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFramerateUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cameraGroupId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.backendFramerate = FramerateData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.frontendFramerate = FramerateData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FramerateUpdate>): FramerateUpdate {
    return FramerateUpdate.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FramerateUpdate>): FramerateUpdate {
    const message = createBaseFramerateUpdate();
    message.cameraGroupId = object.cameraGroupId ?? "";
    message.backendFramerate = (object.backendFramerate !== undefined && object.backendFramerate !== null)
      ? FramerateData.fromPartial(object.backendFramerate)
      : undefined;
    message.frontendFramerate = (object.frontendFramerate !== undefined && object.frontendFramerate !== null)
      ? FramerateData.fromPartial(object.frontendFramerate)
      : undefined;
    return message;
  },
};

function createBaseFramerateData(): FramerateData {
  return { fps: 0, frameTimeMs: 0, source: "", recentFrameDurations: [] };
}

export const FramerateData: MessageFns<FramerateData> = {
  encode(message: FramerateData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fps !== 0) {
      writer.uint32(9).double(message.fps);
    }
    if (message.frameTimeMs !== 0) {
      writer.uint32(17).double(message.frameTimeMs);
    }
    if (message.source !== "") {
      writer.uint32(26).string(message.source);
    }
    writer.uint32(34).fork();
    for (const v of message.recentFrameDurations) {
      writer.double(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FramerateData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFramerateData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.fps = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.frameTimeMs = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 4: {
          if (tag === 33) {
            message.recentFrameDurations.push(reader.double());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.recentFrameDurations.push(reader.double());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FramerateData>): FramerateData {
    return FramerateData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FramerateData>): FramerateData {
    const message = createBaseFramerateData();
    message.fps = object.fps ?? 0;
    message.frameTimeMs = object.frameTimeMs ?? 0;
    message.source = object.source ?? "";
    message.recentFrameDurations = object.recentFrameDurations?.map((e) => e) || [];
    return message;
  },
};

/** Service definition */
export type SkellycamServiceDefinition = typeof SkellycamServiceDefinition;
export const SkellycamServiceDefinition = {
  name: "SkellycamService",
  fullName: "skellycam.SkellycamService",
  methods: {
    /** Stream camera frames to the client */
    streamMultiFrames: {
      name: "StreamMultiFrames",
      requestType: MultiFrameRequest,
      requestStream: false,
      responseType: MultiFrameResponse,
      responseStream: true,
      options: {},
    },
    /** Send frame acknowledgment from client to server */
    acknowledgeMultiFrame: {
      name: "AcknowledgeMultiFrame",
      requestType: MultiFrameAcknowledgment,
      requestStream: false,
      responseType: AcknowledgmentResponse,
      responseStream: false,
      options: {},
    },
    /** Stream log messages to the client */
    streamLogs: {
      name: "StreamLogs",
      requestType: LogRequest,
      requestStream: false,
      responseType: LogRecord,
      responseStream: true,
      options: {},
    },
    /** Stream framerate updates to the client */
    streamFramerates: {
      name: "StreamFramerates",
      requestType: FramerateRequest,
      requestStream: false,
      responseType: FramerateUpdate,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface SkellycamServiceImplementation<CallContextExt = {}> {
  /** Stream camera frames to the client */
  streamMultiFrames(
    request: MultiFrameRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<MultiFrameResponse>>;
  /** Send frame acknowledgment from client to server */
  acknowledgeMultiFrame(
    request: MultiFrameAcknowledgment,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<AcknowledgmentResponse>>;
  /** Stream log messages to the client */
  streamLogs(
    request: LogRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<LogRecord>>;
  /** Stream framerate updates to the client */
  streamFramerates(
    request: FramerateRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<FramerateUpdate>>;
}

export interface SkellycamServiceClient<CallOptionsExt = {}> {
  /** Stream camera frames to the client */
  streamMultiFrames(
    request: DeepPartial<MultiFrameRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<MultiFrameResponse>;
  /** Send frame acknowledgment from client to server */
  acknowledgeMultiFrame(
    request: DeepPartial<MultiFrameAcknowledgment>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<AcknowledgmentResponse>;
  /** Stream log messages to the client */
  streamLogs(request: DeepPartial<LogRequest>, options?: CallOptions & CallOptionsExt): AsyncIterable<LogRecord>;
  /** Stream framerate updates to the client */
  streamFramerates(
    request: DeepPartial<FramerateRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<FramerateUpdate>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
