# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SharedData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CameraFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCameraFrame(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CameraFrame()
        x.Init(buf, n + offset)
        return x

    # CameraFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CameraFrame
    def CameraId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CameraFrame
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CameraFrame
    def FrameNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CameraFrame
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CameraFrame
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CameraFrame
    def Pixels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CameraFrame
    def PixelsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CameraFrame
    def PixelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CameraFrame
    def PixelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def CameraFrameStart(builder): builder.StartObject(6)
def CameraFrameAddCameraId(builder, cameraId): builder.PrependUint32Slot(0, cameraId, 0)
def CameraFrameAddTimestamp(builder, timestamp): builder.PrependUint64Slot(1, timestamp, 0)
def CameraFrameAddFrameNumber(builder, frameNumber): builder.PrependUint32Slot(2, frameNumber, 0)
def CameraFrameAddWidth(builder, width): builder.PrependUint32Slot(3, width, 0)
def CameraFrameAddHeight(builder, height): builder.PrependUint32Slot(4, height, 0)
def CameraFrameAddPixels(builder, pixels): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(pixels), 0)
def CameraFrameStartPixelsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def CameraFrameEnd(builder): return builder.EndObject()
