# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SharedData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SharedMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSharedMessage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SharedMessage()
        x.Init(buf, n + offset)
        return x

    # SharedMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SharedMessage
    def Magic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 3735928559

    # SharedMessage
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SharedMessage
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from SharedData.CameraFrame import CameraFrame
            obj = CameraFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SharedMessage
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from SharedData.SystemStatus import SystemStatus
            obj = SystemStatus()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SharedMessageStart(builder): builder.StartObject(4)
def SharedMessageAddMagic(builder, magic): builder.PrependUint32Slot(0, magic, 3735928559)
def SharedMessageAddSequence(builder, sequence): builder.PrependUint64Slot(1, sequence, 0)
def SharedMessageAddFrame(builder, frame): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(frame), 0)
def SharedMessageAddStatus(builder, status): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)
def SharedMessageEnd(builder): return builder.EndObject()
