# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SharedData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSystemStatus(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemStatus()
        x.Init(buf, n + offset)
        return x

    # SystemStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemStatus
    def Fps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SystemStatus
    def CpuUsage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SystemStatus
    def ActiveCameras(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SystemStatus
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SystemStatusStart(builder): builder.StartObject(4)
def SystemStatusAddFps(builder, fps): builder.PrependFloat32Slot(0, fps, 0.0)
def SystemStatusAddCpuUsage(builder, cpuUsage): builder.PrependFloat32Slot(1, cpuUsage, 0.0)
def SystemStatusAddActiveCameras(builder, activeCameras): builder.PrependUint32Slot(2, activeCameras, 0)
def SystemStatusAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def SystemStatusEnd(builder): return builder.EndObject()
