import React, { createContext, useCallback, useEffect, useState } from 'react';
import { useElectronIPC } from '@/services';
import { isTauri } from '@/services/tauri-ipc/tauri-detection';
import { check } from '@tauri-apps/plugin-updater';

export type UpdateStatus =
    | 'idle'
    | 'checking'
    | 'available'
    | 'downloading'
    | 'ready'
    | 'error'
    | 'up-to-date';

export interface AutoUpdateState {
    status: UpdateStatus;
    version: string | null;
    progress: number;
    errorMessage: string | null;
    checkForUpdate: () => void;
    installUpdate: () => void;
}

export const AutoUpdateContext = createContext<AutoUpdateState | null>(null);

export const AutoUpdateProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const { isElectron, api } = useElectronIPC();
    const [status, setStatus] = useState<UpdateStatus>('idle');
    const [version, setVersion] = useState<string | null>(null);
    const [progress, setProgress] = useState(0);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);

    // ── checkForUpdate ──────────────────────────────────────

    const checkForUpdate = useCallback(async () => {
        if (!isElectron && !isTauri()) return;

        setStatus('checking');
        setErrorMessage(null);

        try {
            // Tauri: use the updater plugin directly
            if (isTauri()) {
                const update = await check();
                if (update) {
                    setStatus('available');
                    setVersion(update.version ?? null);
                } else {
                    setStatus('up-to-date');
                }
                return;
            }

            // Electron: use the tRPC API
            if (api) {
                const result = await api.app.checkForUpdate.mutate();
                if (result.available) {
                    setStatus('available');
                    setVersion(result.version ?? null);
                } else {
                    setStatus('up-to-date');
                }
            }
        } catch (err) {
            setStatus('error');
            const baseMsg = err instanceof Error ? err.message : String(err);
            if (isTauri()) {
                setErrorMessage(
                    `Update check failed: ${baseMsg}\n\n` +
                    `The Tauri updater tried to fetch a release manifest from:\n` +
                    `  https://github.com/freemocap/skellycam/releases/latest/download/latest.json\n\n` +
                    `This file is generated by 'tauri build' and uploaded as part of a GitHub Release. ` +
                    `If you're running a development build or this is the first Tauri release, ` +
                    `this is expected — there are no published Tauri updates yet.`
                );
            } else {
                setErrorMessage(`Update check failed: ${baseMsg}`);
            }
        }
    }, [isElectron, api]);

    // ── installUpdate ───────────────────────────────────────

    const installUpdate = useCallback(async () => {
        try {
            // Tauri: download + install via the updater plugin
            if (isTauri()) {
                const update = await check();
                if (!update) {
                    setStatus('error');
                    setErrorMessage(
                        'No update available to install.\n\n' +
                        'This means no newer version was found at:\n' +
                        '  https://github.com/freemocap/skellycam/releases/latest/download/latest.json\n\n' +
                        'The current version (' + (version || 'unknown') + ') is either the latest or ' +
                        'no Tauri releases have been published yet.'
                    );
                    return;
                }
                setStatus('downloading');
                await update.downloadAndInstall();
                // The app will restart after install, so we don't change status further
                return;
            }

            // Electron: trigger install via IPC
            if (api) {
                api.app.installUpdate.mutate();
            }
        } catch (err) {
            setStatus('error');
            const baseMsg = err instanceof Error ? err.message : String(err);
            setErrorMessage(`Update install failed: ${baseMsg}`);
        }
    }, [api, version]);

    // ── Listen for Electron push events from UpdateHandler ──

    useEffect(() => {
        if (!isElectron || !window.electronAPI) return;

        const cleanups = [
            window.electronAPI.onUpdateAvailable((info) => {
                setStatus('available');
                setVersion(info.version);
            }),
            window.electronAPI.onDownloadProgress((prog) => {
                setStatus('downloading');
                setProgress(prog.percent);
            }),
            window.electronAPI.onUpdateDownloaded((info) => {
                setStatus('ready');
                setVersion(info.version);
            }),
            window.electronAPI.onUpdateError((error) => {
                setStatus('error');
                setErrorMessage(error.message);
            }),
        ];

        return () => {
            cleanups.forEach((cleanup) => cleanup());
        };
    }, [isElectron]);

    // ── Periodic check (Tauri) — every 4 hours ─────────────

    useEffect(() => {
        if (!isTauri()) return;

        // Initial check 10s after mount
        const initialTimer = setTimeout(() => {
            checkForUpdate();
        }, 10_000);

        // Periodic check every 4 hours
        const interval = setInterval(() => {
            checkForUpdate();
        }, 4 * 60 * 60 * 1000);

        return () => {
            clearTimeout(initialTimer);
            clearInterval(interval);
        };
    }, [checkForUpdate]);

    // ── Listen for menu-triggered check-for-updates ────────

    useEffect(() => {
        const handler = () => checkForUpdate();
        window.addEventListener('check-for-updates', handler);
        return () => window.removeEventListener('check-for-updates', handler);
    }, [checkForUpdate]);

    return (
        <AutoUpdateContext.Provider value={{ status, version, progress, errorMessage, checkForUpdate, installUpdate }}>
            {children}
        </AutoUpdateContext.Provider>
    );
};
