//! Verify and auto-generate state machine diagram artifacts.
//!
//! The `StateDiagram` trait on Camera and CameraGroup is the source of truth.
//! These tests:
//! 1. Verify the trait output is well-formed and contains all expected states.
//! 2. Write the auto-generated Mermaid to `.md` files in `docs/state_machines/`.
//!
//! The hand-written XState HTML visualizers that used to live alongside the
//! `.md` files have been removed (they documented an older `barrier-then-capture`
//! design that the code no longer implements). The `.md` files are now the
//! single source of truth for the rendered diagrams.

use std::path::Path;

use skellycam::camera::state_machine::{Camera, Disconnected, StateDiagram};
use skellycam::camera_group::state_machine::{CameraGroup, Empty};

// ── Paths ───────────────────────────────────────────────────────────────────

const DOCS_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/docs/state_machines");
const CAMERA_MD: &str = "camera_state_machine.md";
const GROUP_MD: &str = "camera_group_state_machine.md";

// ── Helpers ─────────────────────────────────────────────────────────────────

/// Write content to a file, creating parent directories if needed.
/// Panics on I/O error (test infrastructure failure, not a code bug).
fn write_doc_file(filename: &str, content: &str) {
    let dir = Path::new(DOCS_DIR);
    std::fs::create_dir_all(dir).unwrap();
    let path = dir.join(filename);

    // Only write if content changed — avoids unnecessary git diffs
    if let Ok(existing) = std::fs::read_to_string(&path) {
        if existing == content {
            return;
        }
    }
    std::fs::write(&path, content).unwrap();
    eprintln!("  Updated: {}", path.display());
}

// ── Tests: Mermaid trait output is correct ──────────────────────────────────

#[test]
fn camera_mermaid_contains_all_states() {
    let diagram = Camera::<Disconnected>::mermaid_state_diagram();
    assert!(!diagram.is_empty());
    assert!(diagram.starts_with("stateDiagram-v2"));

    for state in &[
        "Disconnected", "Enumerated", "Configuring", "Streaming",
        "ShuttingDown", "Faulted", "WaitingForFrame",
        "AtBarrier", "Capturing", "Sending",
    ] {
        assert!(diagram.contains(state), "missing state: {state}");
    }
}

#[test]
fn camera_group_mermaid_contains_all_states() {
    let diagram = CameraGroup::<Empty>::mermaid_state_diagram();
    assert!(!diagram.is_empty());
    assert!(diagram.starts_with("stateDiagram-v2"));

    for state in &[
        "Empty", "Configured", "Streaming", "ShuttingDown", "Stopped",
        "Active", "Paused", "NotRecording", "Recording",
        "CollectingFrames", "AllFramesReceived", "WaitingAtBarrier",
        "AssemblingPayload", "SendingDownstream",
    ] {
        assert!(diagram.contains(state), "missing state: {state}");
    }
}

// ── Tests: auto-generate .md files from trait output ────────────────────────

#[test]
fn write_camera_mermaid_to_docs() {
    let diagram = Camera::<Disconnected>::mermaid_state_diagram();
    let md = format!(
        "<!-- Auto-generated by tests/state_diagrams.rs — do not edit by hand. -->\n\
         <!-- Source of truth: src/camera/state_machine.rs StateDiagram impl. -->\n\n\
         # Camera State Machine\n\n\
         ```mermaid\n{diagram}\n```\n"
    );
    write_doc_file(CAMERA_MD, &md);
}

#[test]
fn write_camera_group_mermaid_to_docs() {
    let diagram = CameraGroup::<Empty>::mermaid_state_diagram();
    let md = format!(
        "<!-- Auto-generated by tests/state_diagrams.rs — do not edit by hand. -->\n\
         <!-- Source of truth: src/camera_group/state_machine.rs StateDiagram impl. -->\n\n\
         # CameraGroup State Machine\n\n\
         ```mermaid\n{diagram}\n```\n"
    );
    write_doc_file(GROUP_MD, &md);
}
