[package]
name = "skellycam"
version = "2.0.0-alpha.5"
description = "SkellyCam - the camera backend for the FreeMoCap software"
authors = ["Skelly FreeMocap <info@freemocap.org>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/freemocap/skellycam"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-fs = "2"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["process", "io-util"] }
