// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file skellycam.proto (package skellycam, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AcknowledgmentResponse, FramerateRequest, FramerateUpdate, LogRecord, LogRequest, MultiFrameAcknowledgment, MultiFrameRequest, MultiFrameResponse } from "./skellycam_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition
 *
 * @generated from service skellycam.SkellycamService
 */
export const SkellycamService = {
  typeName: "skellycam.SkellycamService",
  methods: {
    /**
     * Stream camera frames to the client
     *
     * @generated from rpc skellycam.SkellycamService.StreamMultiFrames
     */
    streamMultiFrames: {
      name: "StreamMultiFrames",
      I: MultiFrameRequest,
      O: MultiFrameResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Send frame acknowledgment from client to server
     *
     * @generated from rpc skellycam.SkellycamService.AcknowledgeMultiFrame
     */
    acknowledgeMultiFrame: {
      name: "AcknowledgeMultiFrame",
      I: MultiFrameAcknowledgment,
      O: AcknowledgmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stream log messages to the client
     *
     * @generated from rpc skellycam.SkellycamService.StreamLogs
     */
    streamLogs: {
      name: "StreamLogs",
      I: LogRequest,
      O: LogRecord,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Stream framerate updates to the client
     *
     * @generated from rpc skellycam.SkellycamService.StreamFramerates
     */
    streamFramerates: {
      name: "StreamFramerates",
      I: FramerateRequest,
      O: FramerateUpdate,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

