- module-name: 'skellycam.api.http.ui'
  data-files:
    patterns:
      - 'skellycam/api/http/ui/ui.html'

- module-name: 'shared.skellycam-logo'
  data-files:
    patterns:
      - 'shared/skellycam-logo/skellycam-favicon.ico'

# - module-name: 'pyaudio'
#   dlls:
#     - from_filenames:
#         relative_path: '_sounddevice_data/portaudio-binaries'
#         prefixes:
#           - 'libportaudio'
#       when: 'macos'
