from skellycam.frontend.application.app_state_manager import get_or_create_app_state_manager
from skellycam.frontend.application.qt_application import create_or_recreate_qt_application


app_state_manager = get_or_create_app_state_manager()
