# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import skellycam_pb2 as skellycam__pb2


class SkellycamServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMultiFrames = channel.unary_stream(
                '/skellycam.SkellycamService/StreamMultiFrames',
                request_serializer=skellycam__pb2.MultiFrameRequest.SerializeToString,
                response_deserializer=skellycam__pb2.MultiFrameResponse.FromString,
                _registered_method=True)
        self.AcknowledgeMultiFrame = channel.unary_unary(
                '/skellycam.SkellycamService/AcknowledgeMultiFrame',
                request_serializer=skellycam__pb2.MultiFrameAcknowledgment.SerializeToString,
                response_deserializer=skellycam__pb2.AcknowledgmentResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/skellycam.SkellycamService/StreamLogs',
                request_serializer=skellycam__pb2.LogRequest.SerializeToString,
                response_deserializer=skellycam__pb2.LogRecord.FromString,
                _registered_method=True)
        self.StreamFramerates = channel.unary_stream(
                '/skellycam.SkellycamService/StreamFramerates',
                request_serializer=skellycam__pb2.FramerateRequest.SerializeToString,
                response_deserializer=skellycam__pb2.FramerateUpdate.FromString,
                _registered_method=True)


class SkellycamServiceServicer(object):
    """Service definition
    """

    def StreamMultiFrames(self, request, context):
        """Stream camera frames to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeMultiFrame(self, request, context):
        """Send frame acknowledgment from client to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Stream log messages to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFramerates(self, request, context):
        """Stream framerate updates to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkellycamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMultiFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMultiFrames,
                    request_deserializer=skellycam__pb2.MultiFrameRequest.FromString,
                    response_serializer=skellycam__pb2.MultiFrameResponse.SerializeToString,
            ),
            'AcknowledgeMultiFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeMultiFrame,
                    request_deserializer=skellycam__pb2.MultiFrameAcknowledgment.FromString,
                    response_serializer=skellycam__pb2.AcknowledgmentResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=skellycam__pb2.LogRequest.FromString,
                    response_serializer=skellycam__pb2.LogRecord.SerializeToString,
            ),
            'StreamFramerates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFramerates,
                    request_deserializer=skellycam__pb2.FramerateRequest.FromString,
                    response_serializer=skellycam__pb2.FramerateUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skellycam.SkellycamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skellycam.SkellycamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkellycamService(object):
    """Service definition
    """

    @staticmethod
    def StreamMultiFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/skellycam.SkellycamService/StreamMultiFrames',
            skellycam__pb2.MultiFrameRequest.SerializeToString,
            skellycam__pb2.MultiFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeMultiFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skellycam.SkellycamService/AcknowledgeMultiFrame',
            skellycam__pb2.MultiFrameAcknowledgment.SerializeToString,
            skellycam__pb2.AcknowledgmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/skellycam.SkellycamService/StreamLogs',
            skellycam__pb2.LogRequest.SerializeToString,
            skellycam__pb2.LogRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFramerates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/skellycam.SkellycamService/StreamFramerates',
            skellycam__pb2.FramerateRequest.SerializeToString,
            skellycam__pb2.FramerateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
